# Generated by Django 4.2.1 on 2023-05-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0004_branch_profile_branchs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='branchs',
        ),
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.ManyToManyField(to='myauth.branch'),
        ),
    ]
