# Generated by Django 4.2.1 on 2023-05-23 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0009_alter_profile_email_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='branch',
        ),
        migrations.AddField(
            model_name='profile',
            name='branch',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='myauth.branch'),
            preserve_default=False,
        ),
    ]
