# Generated by Django 4.2.1 on 2023-05-23 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0010_remove_profile_branch_profile_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myauth.branch'),
        ),
    ]
